### ISSUE TITLE
After last update getting error

### ISSUE THREAD

**Issue by abalmush** [nfroidure/gulp-svgicons2svgfont#36] opened 2017-07-17 08:27 UTC
```
/node_modules/gulp-svgicons2svgfont/src/index.js:38
    gutil.log(...['gulp-svgicons2svgfont:'].concat(
              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by nfroidure** [comment] 2017-07-17 09:07
Hi, this is a duplicate of https://github.com/nfroidure/gulp-svgicons2svgfont/issues/35

Should have bumped a major version, I'll fix it but in the meanwhile you should revert or update your Node version.

**Closed** 2017-07-17 09:21 UTC
